version: '3'

services:
  frontend:
    image: apecee/portfolio_website:portfolio_website_frontend_0.0.2
    ports:
      - "80:4200"  # Maps port 4200 from container to port 80 on host (standard HTTP port)
    restart: always
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      # Add this if your frontend needs to know the backend URL
      - BACKEND_URL=http://backend:8000

  backend:
    image: apecee/portfolio_website:portfolio_website_backend_0.0.2
    ports:
      - "8000:8000"
    restart: always
    environment:
      # Add any environment variables your FastAPI backend needs
      - PYTHONUNBUFFERED=1


networks:
  default:
    driver: bridge