version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    image: apecee/portfolio_website:portfolio_website_frontend_0.0.4
    expose:
      - "4200"
    restart: always
    depends_on:
      - backend
#    environment:
#      - NODE_ENV=production

  backend:
    image: apecee/portfolio_website:portfolio_website_backend_0.0.6
    expose:
      - "8000"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production

networks:
  default:
    driver: bridge